server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 9099
  minThreads: 1
  maxThreads: 64
  idleThreadTimeout: 1s
  allowedMethods:
    - "GET"
    - "POST"

serviceName: orders
serviceId: 541
servicePort: 9099
serviceAddress: 127.0.0.1